function(doc) {
    // Ignore thing that aren't merged changes generated by humans
    if (doc.type !== 'change-merged' ||
        doc.change.subject.indexOf("MARKED") != -1 ||
        doc.change.branch == 'toy-build' ||
        doc.ignored) {
        return;
    }
    // Need to canonicalize the actor
    var actor = [doc.change.owner.name, doc.change.owner.name.split(' ')[0],
                 doc.change.owner.email];
    emit([actor, doc.project], 1);
}
