function(doc) {
    // Ignore thing that aren't merged changes generated by humans
    if (doc.type !== 'change-merged' ||
        doc.change.subject.indexOf("MARKED") != -1 ||
        doc.change.branch == 'toy-build') {
        return;
    }
    // Need to canonicalize the actor
    var ob = {};
    ob[doc.project] = 1;
    var actor = [doc.change.owner.name, doc.change.owner.name.split(' ')[0],
                 doc.change.owner.email];
    emit([actor, doc.ts.split('T')[0]], ob);
}
